### ISSUE TITLE
Does not work in Sketch 49.1

### ISSUE THREAD

**Issue by nielsemann** [emrerussia/sketch-clear-export-options#2]
I've tried runnding your plugin in Sketch 49.1 but nothing happens. Will you update it any time soon?

**Comment by petrchutny** [comment]
Same for Sketch 51.3. Your plugin idea is great, I have to say that I would benefit from it a lot :) Thanks for making it!

**Comment by emrerussia** [comment]
Thanks guys! I've updated the plugin, now it works with the latest Sketch.
@petrchutny I hope i wasn't too late and you can still benefit from it :) Thanks a lot for your message!
